---
title: "General Policies"
subtitle: <font size="4">Professor Noli Brazil</font>
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: flatly
    self_contained: false
---

<style>
h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

</style>

<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>

\


This page provides information on the lab's culture, how to join the lab, and the general workflow for starting up and working on project tasks.

<div style="margin-bottom:25px;">
</div>
## **Lab Culture**
\

The culture of the Neighborhood Inequality Lab is collaborative, inclusive, supportive, and free from discrimination.  Our community has high standards for rigor, quality, and ethics, and supports each other to reach these objectives. Because the concept of a lab culture is "squishy", below are distinguishing features of our lab's culture.  

* We have mutual respect for all lab members. This is demonstrated by accomplishing tasks by the agreed upon deadlines, starting/ending meetings at the scheduled time, and being prepared to discuss and engage, which includes drafting agendas if moderating a discussion. This is also demonstrated by practicing active listening, and not dominating conversations.
* Mutual respect is also demonstrated by providing respectful, honest input to all team members, and being open to receiving input from others regardless of level/position.
* Mutual respect also means being understanding of others. We are coming from different life stages and backgrounds, and are dealing with different life stressors. We are compassionate to lab members, and treat each other with grace and empathy.
* We also are compassionate to ourselves. We strive for quality and rigor, but also balance that with self-compassion when times get tough.
* Part of being compassionate to yourself and to others is to ask for help, and to offer help when you can. This includes asking//providing help for all aspects of the research process, including data analysis and writing, and career advice. Be present during meetings and gatherings, respond to inquiries when someone posts a question or expresses a need, and check in with each other, especially when you know someone may be going through a stressful experience.
* The lab is highly multidisciplinary. This is intentional because Dr. Brazil's academic and career background is multidisciplinary, and he believes the types of issues and problems the lab addresses require a multidisciplinary approach. Part of understanding others is to not only respect  others' disciplinary orientations, but use this to our advantage in terms of broadening our development as social science scholars and practitioners. 
* We do not promote a culture of overwork. Professor Brazil does not expect members to be working in the evenings or on weekends, and asks that members respect all lab members’ evening and weekend time as well. This includes not expecting members to review your work product, or otherwise be available for typical work tasks outside business hours.
* Have fun. Make jokes. Laugh. Yes, always strive to be professional with one another, but also make room to connect with other lab members, being respectful of their boundaries.

<div style="margin-bottom:25px;">
</div>
## **Joining**
\

There are multiple ways you can join the group. 

* Graduate student
  + Professor Brazil hires you as a Graduate Student Researcher.
  + Professor Brazil is your major advisor or co-advisor.
  + Professor Brazil is on your dissertation/thesis committee, and your research interests align with the types of projects supported by the lab.

* Undergraduate student
  + Professor Brazil hires you as a Research Assistant.
  + You work on one of the lab's projects voluntarily, enrolled for credit, or to fulfill your internship requirements.
  + Professor Brazil is your senior thesis advisor, and the project is aligned with the types of projects supported by the lab.
  
  
For more details on how to join, see guidelines and advice summarized [here](). Note that because of limited space, limited resources or lack of fit, the lab may not be able to bring you in as a member. 


<div style="margin-bottom:25px;">
</div>
### **General Workflow**
\

Once it is settled that you are joining the lab, below is an outline of the general workflow for setting yourself up in the lab. Fuller details for many of these steps are provided in the rest of this guide.

1. Decide on which project to work on (if not recruited by Professor Brazil to work on a specific project). This will involve taking one or more of the following actions: talking to Prof. Brazil and other lab members, reading project material, and attending project meetings.
2. For undergraduates, decide whether to be involved in the project as a paid Research Assistant, enrolled for credit, to fulfill internship requirements, or to fulfill an Honors thesis or some other research program (e.g., McNair).
3. Meet with Professor Brazil to set expectations and goals, ask questions, and iron out logistics. He will also likely recommend reading some material to get yourself further acquainted with the project.
4. Get access to and acquaint yourself with the Google shared drive project folder.
5. Download Slack, and join the lab's Slack group. Introduce yourself to everyone in the general channel.
6. If you would like access to the lab office space, indicate so during your initial meeting with Professor Brazil. You will need to fill out a form, and get the key from the department's office administrator.
7. You will get a calendar invite for the regularly scheduled meetings for the quarter. Accept the invite to acknowledge your receipt.
8. As a paid GSR or RA, you will be required to go through various online, self-paced webinars. These will cover various subjects, including cyber security and research ethics. Paid RAs are expected to log their hours in a timesheet they submit every two weeks.
9. Start the project! See the Project Workflow section below.

<div style="margin-bottom:25px;">
</div>
## **Lab Space**
\

The Neighborhood Inequality Lab has it's own office space located in Hart Hall. The space has two desktop computers, a printer, two desks, chairs, bookshelves, white board, coffee and tea maker, and snacks. If you would like to access the lab space, indicate so to Professor Brazil, and he will set you up with the office administrator. You will have access to the lab during business hours, but note that you will likely be sharing the lab space with other members, so please coordinate with them if the space becomes too congested. Also note that the key is for the office space. There is a separate key for the building doors, which close after 6 pm. If you would like to use the lab after business hours, you can stay in the lab, but you can't leave the building and come back in. There is also a break room located on the first floor that you have access to.

It is your responsibility to use the space appropriately,  being respectful to other lab members who use the space, as well as those occupying offices on the same floor.  Please keep the office clean, and avoid being loud. If there is any issues with the lab, which includes identifying something that the lab space needs, please let Professor Brazil know.

<div style="margin-bottom:25px;">
</div>
## **Communication**
\

If you are part of a lab research project, you will work closely with Professor Brazil. For some projects, you may work with a much larger team, with members ranging across undergraduate to masters to PhD level. As such, efficient and clear communication between members is vital to ensure success and engagement. 

<div style="margin-bottom:25px;">
</div>
### **Slack**
\

When you join the lab, you will be expected to join the neighborhood inequality lab Slack platform. We use Slack because it's free, has many easy to use messaging features, and all the cool kids are using it. Access Slack either through your cell phone, desktop or online internet browser.  If you don't already have slack, download it [here](https://slack.com/), and you will get an invite from Professor Brazil. 

Here's what you will find and do on Slack:

* Post and read about your project. These include
  + A summary of meetings
  + A summary of next steps
  + Quick updates
  + Project related questions that are relevant to all team members
  + Scheduling meetings
* Read about and contribute to what lab members are doing in other lab projects
* Post, read and contribute to questions open to every lab member about
  + code, data wrangling, data analysis, writing or anything related to the the research process
  + classes, graduate programs, and other career-related topics
* Post and read about announcements for jobs, grants and fellowships, seminars, conferences
* You can also direct message (DM) members to discuss private issues

Slack is organized by channel. Each channel is specific to the lab project. There is also a channel for  code and data analysis related posts (e.g., how can I do this in R? Which spatial model should I run?), announcements (E.g., job postings, when our next end of the quarter celebrations are), and general posts. You can allow for notifications if someone posts, or DMs you. Please make an effort to respond to messages that message you as quickly as possible.

Of course, *using* Slack is voluntary. And if you find yourself writing a really long post, perhaps it is better to send an email, or wait to ask your question during a meeting.  Professor Brazil will communicate through both email and Slack.

<div style="margin-bottom:25px;">
</div>
### **Meetings**
\

You are expected to meet with team members as a group on a regular basis. Depending on how many team members, and your specific responsibilities, you may also need to separately meet with some members. Usually, full team meetings are held every week, especially at the beginning of the project, but this may change depending on the broader project tasks. For example, we will likely meet every week during data wrangling and data analysis, but less regularly during the writing stage, and potentially not at all for awhile when a paper is submitted for journal peer review. Regularly scheduled are usually set at the beginning of each quarter, with the understanding that days/times may change.

Meetings typically involve going through updates from each members,  addressing questions and concerns, and establishing next steps. There's also always time set aside at the beginning of each meeting for general updates, questions, and the sharing of stories/haikus/sonnets/op-eds.

Professor Brazil prefers to have meetings in person at his office as the default, with the option to meet on Zoom given changes in schedules and other unexpected occurrences, such as travel or a minor illness like a modest cold (if major, you should not meet at all). However, several students do not live locally, or have other life circumstances that make it difficult to meet regularly in person, so we hold Zoom-only meetings for some projects.

If you have a question that is preventing you from moving forward with your task, do not save it for the team meeting, but reach out to the team, or Professor Brazil directly. He will either address it via email/slack, or ask to meet with you if the issue is difficult to address through email/slack. 

<div style="margin-bottom:25px;">
</div>
#### **Advising on your work**
\

If you are a student meeting with Professor Brazil to ask questions about your dissertation/thesis or a research project separate from those conducted in this lab, please adhere to following guidelines:

* Send an email providing context for your project. Some questions can be addressed by email instead of an in person meeting. 
* If a meeting is needed, give Professor Brazil enough time flexibility to schedule one (e.g., do not ask just to meet that afternoon or the next day, with no other options), unless it is urgent (e.g., I need to send a draft of my thesis to the committee, but I need your feedback). 
* Send relevant material well in advance of the meeting, preferably no less than 5 days before the meeting. This may be the draft of your dissertation/thesis, or a few paragraphs providing context to your questions.
  + If you send material close to the meeting date, do not expect Professor Brazil to thoroughly read the material. 
* Send a written agenda for the meeting through email before the meeting, even if it is a few hours in advance. 
* The reasons why we want you to provide the materials outlined above is so that we can be efficient with our time during the meeting, which includes Professor Brazil providing you the best possible and informed advice.


<div style="margin-bottom:25px;">
</div>
## **Project Workflow**
\

Lab projects are primarily quantitative. This means that you will likely be involved in tasks throughout the data analysis process. You will also likely be involved in non data analysis tasks, such as reading papers, literature reviews, writing up summaries, contributing to manuscripts intended to be published in peer-review academic journals, which includes writing but also formatting and adding references, and helping present results through PowerPoint presentations, StoryMaps, web maps, etc.

The types of specific tasks and quantitative methods you will employ will depend on the project.  But below are project workflow components that are generally common to all projects.

<div style="margin-bottom:25px;">
</div>
### **Folder Management**
\

We use Google Drive to store all project related documents, including data, code and analysis output. As a UC Davis student, you have access to a lot of memory space on Google drive. You can access it through your web browser. But we will ask you to download Google Drive for your desktop (see [here](https://www.google.com/drive/download/)). This will allow you to access Drive folders through your computer's management system. This will also allow you to use directly link R to shared folder data by setting your working directory directly to the shared drive.

Although each project is unique, you will find the following folders associated with the project:

* References: Papers and reports conducted by other researchers on subjects informing/relevant to the project 
* Data: Raw and cleaned data files
* Code: R scripts 
* Results: Tables, maps, graphs, and modelling results.
* Writing: Documents summarizing project findings, including manuscripts being prepared for submission to a peer-reviewed journal.
* Presentations: Documents related to presentations of our project (e.g., at conferences)



<div style="margin-bottom:25px;">
</div>
### **Code/Data**
\

We use the statistical program R for all data wrangling and analysis tasks. A few best practices with data and code management:

* When you download raw data, save it to the appropriate folder, and always wrangle it through R scripts. Never overwrite the original file. Once it is cleaned, save it as a new file
* Rather than dumping all the files in one single Data folder, create sub-folders within the data folder organized by type. For example, one folder could be demographics, another folder is for another distinct type of data (e.g., crime).
* We use R Scripts for data wrangling. We may also use them for the exploratory and modelling stages of the project. We use R Markdowns when we need to present results, such as a set of graphs and descriptive statistics in the exploratory data analysis stage.
* Always start your R Code with a a file header that provides a brief summary of what it is doing. Indicate yourself as the author, and put the date you first created, and another date for when you last edited. And always provide comments to each line of your code. An example of a file header is shown below

```{r}
##########################################################
##This R Script generates demographic data for 18 U.S.
#cities at the block group level. 
#
#
#Created by: Brittany Vang
#Month/Year created: February 2023
#Last edited by Noli Brazil:  June 2023
#Month/Year last edited: February 2023
##########################################################
```

* Other team members will likely use your code, including members that join the team after you've left, so it is important to comment. If you go into someone else's code to edit/change something, add the edit date, and indicate what changes you made (put your initials).

<div style="margin-bottom:25px;">
</div>
### **Remote High Performance Computing**
\

Some tasks based on the size of the data and the memory intensity of the statistical models may require memory space beyond what is offered in your personal computer or the lab computers. In this case, you can access UC Davis [High Performance Computing (HPC)](https://datalab.ucdavis.edu/remote-high-performance-computing/). This will allow you to store data and run models through a remote cluster, which is as a group of interconnected computers that work together to perform computationally intensive tasks. The cluster you will access depends on which college you are affiliated with. Because Professor Brazil is affiliated with the College of Agricultural and Environmental Sciences (CAES), he access the [FARM cluster](https://hpc.ucdavis.edu/farm-cluster). 



<div style="margin-bottom:25px;">
</div>
### **Presentations**
\

It is likely that project findings will be presented to an audience outside of your project team at some point during the project. This includes:

* We will present results to the lab group to get feedback and reaction.
* We will present results at a professional conference. This is usually a PowerPoint presentation, but also can be a [poster](https://urc.ucdavis.edu/creating-effective-academic-posters). 
* Undergraduates are expected to present at the yearly UC Davis [undergraduate research conference](https://urc.ucdavis.edu/conference), which involves putting a poster together and presenting it at an hour long session.
* If you are a graduate student doing a research rotation or research units with Professor Brazil, then you will present results to your program's committee for the former, or to the lab for the latter.


<div style="margin-bottom:25px;">
</div>
### **Publishing**
\

It is expected that project findings will be written up for publication in a [peer-reviewed academic journal](https://www.nlm.nih.gov/oet/ed/stats/03-700.html). You will be included as a co-author on the paper as long as you substantively contribute to the project. Although this will discussed by team members based on the project,  guidelines on what determines inclusion in authorship can be found [here](https://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html). In general, authorship is based on the following criteria:

* Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; AND
* Drafting the work or revising it critically for important intellectual content; AND
* Final approval of the version to be published; AND
* Agreement to be accountable for all aspects of the work in ensuring that questions related to the accuracy or integrity of any part of the work are appropriately investigated and resolved.

We will discuss authorship early in the research process and have continuing conversations regarding team member roles. 

When we select journals for publication, we will prioritize publishing in journals that offer an Open Access option. However, we realize that sometimes the most appropriate journal for a particular paper will be one that does not offer this option. The UC system provides a relatively generous option for covering open access fees. However, when this funding is not available for open access publication fees, Dr. Brazil will cover these fees using unrestricted funds when possible.



