---
title: "Prospective Students"
subtitle: <font size="4">Professor Noli Brazil</font>
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: flatly
    self_contained: false
---

<style>
h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

</style>

<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>

\

This page provides information on guidelines for prospective students seeking to work with me. 

<div style="margin-bottom:25px;">
</div>
## **Graduate Students**
\

I am affiliated with four UC Davis graduate programs: [Community Development](https://communitydevelopment.ucdavis.edu/), [Geography](https://geography.ucdavis.edu/), [Public Health](https://health.ucdavis.edu/phs/education/ggph_index.html) and [Sociology](https://sociology.ucdavis.edu/graduate). As a member of these groups, I can be the major advisor, and a member on the thesis, dissertation and Qualifying Exam (QE) committees. I can also serve as the outside member for other graduate programs. Feel free to contact me regarding joining your dissertation committee or serving on the qualifying exam, but you will need to provide the following information before I commit. Even if the fit is strong, I may say no because I am over committed at the moment.

<div style="margin-bottom:25px;">
</div>
### **Qualifying Exam**
\

Please send me a maximum one-page summary describing how my specific expertise would contribute to the topics that you envision being tested on for the qualifying exam so I can assess whether it will be beneficial to you. If you are interested in bringing me in only as someone with expertise on a quantitative method (e.g., spatial analysis), explain why you believe I have expert knowledge on that method, why are you interested in having someone with this methodological expertise on your QE committee, what you expect me to test you on for the QE, and whether you searched for faculty with similar methodological expertise but who also has domain knowledge in your substantive topic(s).  Also note when you plan to take your QE, and the members already on your committee. 

Please see my [website](https://nbrazil.faculty.ucdavis.edu/) for information on my academic training and research interests.

<div style="margin-bottom:25px;">
</div>
### **Dissertation/Thesis Committee**
\

Please send me a maximum one-page summary of your dissertation proposal and note the members already on your committee so I can assess whether my expertise will be beneficial to you. Explain how my specific expertise (not just quantitative methods) would contribute to your dissertation research. If you would like me to join the committee only to provide support and guidance on quantitative methods, explain whether you searched for faculty with similar methodological expertise but who also has domain knowledge in your substantive topic(s). 

Please see my [website](https://nbrazil.faculty.ucdavis.edu/) for information on my academic training and research interests.

<div style="margin-bottom:25px;">
</div>
## **Undergraduate Students**
\

I normally do not bring in undergraduate students into the lab unless they have taken one of my classes. Because my research is quantitative, it would be to your benefit to take my [CRD 150](https://crd150.github.io/), Quantitative Methods in Community Research. If you are interested in doing research in my lab, please contact me to set up a time to meet with me, and be prepared to explain why you are interested in doing research with me. 


<div style="margin-bottom:25px;">
</div>
## **Visiting Graduate Students**
\

Given my advising responsibilities at UC Davis, I am not able to host visiting graduate students at UC Davis.


